Rscript bayesian_estimation.R ./data/FKRP_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt All 0.95 ./data/FKRP_All_0.95.txt 
Rscript bayesian_estimation.R ./data/FKRP_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt EUR 0.95 ./data/FKRP_EUR_0.95.txt 
Rscript bayesian_estimation.R ./data/FKRP_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt NFE 0.95 ./data/FKRP_NFE_0.95.txt 
Rscript bayesian_estimation.R ./data/FKRP_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt FIN 0.95 ./data/FKRP_FIN_0.95.txt 
Rscript bayesian_estimation.R ./data/TCAP_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt All 0.95 ./data/TCAP_All_0.95.txt 
Rscript bayesian_estimation.R ./data/TCAP_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt EUR 0.95 ./data/TCAP_EUR_0.95.txt 
Rscript bayesian_estimation.R ./data/TCAP_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt NFE 0.95 ./data/TCAP_NFE_0.95.txt 
Rscript bayesian_estimation.R ./data/TCAP_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt FIN 0.95 ./data/TCAP_FIN_0.95.txt 
Rscript bayesian_estimation.R ./data/ANO5_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt All 0.95 ./data/ANO5_All_0.95.txt 
Rscript bayesian_estimation.R ./data/ANO5_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt EUR 0.95 ./data/ANO5_EUR_0.95.txt 
Rscript bayesian_estimation.R ./data/ANO5_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt NFE 0.95 ./data/ANO5_NFE_0.95.txt 
Rscript bayesian_estimation.R ./data/ANO5_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt FIN 0.95 ./data/ANO5_FIN_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCA_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt All 0.95 ./data/SGCA_All_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCA_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt EUR 0.95 ./data/SGCA_EUR_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCA_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt NFE 0.95 ./data/SGCA_NFE_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCA_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt FIN 0.95 ./data/SGCA_FIN_0.95.txt 
Rscript bayesian_estimation.R ./data/CAPN3_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt All 0.95 ./data/CAPN3_All_0.95.txt 
Rscript bayesian_estimation.R ./data/CAPN3_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt EUR 0.95 ./data/CAPN3_EUR_0.95.txt 
Rscript bayesian_estimation.R ./data/CAPN3_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt NFE 0.95 ./data/CAPN3_NFE_0.95.txt 
Rscript bayesian_estimation.R ./data/CAPN3_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt FIN 0.95 ./data/CAPN3_FIN_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCB_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt All 0.95 ./data/SGCB_All_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCB_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt EUR 0.95 ./data/SGCB_EUR_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCB_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt NFE 0.95 ./data/SGCB_NFE_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCB_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt FIN 0.95 ./data/SGCB_FIN_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCD_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt All 0.95 ./data/SGCD_All_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCD_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt EUR 0.95 ./data/SGCD_EUR_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCD_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt NFE 0.95 ./data/SGCD_NFE_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCD_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt FIN 0.95 ./data/SGCD_FIN_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCG_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt All 0.95 ./data/SGCG_All_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCG_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt EUR 0.95 ./data/SGCG_EUR_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCG_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt NFE 0.95 ./data/SGCG_NFE_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCG_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt FIN 0.95 ./data/SGCG_FIN_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCA_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt All 0.95 ./data/SGCA_All_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCA_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt EUR 0.95 ./data/SGCA_EUR_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCA_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt NFE 0.95 ./data/SGCA_NFE_0.95.txt 
Rscript bayesian_estimation.R ./data/SGCA_mutation_AF_patho.txt ../beta_parameter_prior_ExAC.txt FIN 0.95 ./data/SGCA_FIN_0.95.txt 
