Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/data/data/FKRP_mutation_AF.txt /ysm-gpfs/scratch60/wl382/WES/data/data/FKRP_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/data/data/TCAP_mutation_AF.txt /ysm-gpfs/scratch60/wl382/WES/data/data/TCAP_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/data/data/ANO5_mutation_AF.txt /ysm-gpfs/scratch60/wl382/WES/data/data/ANO5_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/data/data/SGCA_mutation_AF.txt /ysm-gpfs/scratch60/wl382/WES/data/data/SGCA_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/data/data/CAPN3_mutation_AF.txt /ysm-gpfs/scratch60/wl382/WES/data/data/CAPN3_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/data/data/SGCB_mutation_AF.txt /ysm-gpfs/scratch60/wl382/WES/data/data/SGCB_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/data/data/SGCD_mutation_AF.txt /ysm-gpfs/scratch60/wl382/WES/data/data/SGCD_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/data/data/SGCG_mutation_AF.txt /ysm-gpfs/scratch60/wl382/WES/data/data/SGCG_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/data/data/SGCA_mutation_AF.txt /ysm-gpfs/scratch60/wl382/WES/data/data/SGCA_mutation_AF_patho.txt 
