Rscript annotate_pathogenecity_allMissense.R ../data/FKRP_mutation_AF.txt ../data/FKRP_mutation_AF_patho_allMissense.txt 
Rscript annotate_pathogenecity_allMissense.R ../data/TCAP_mutation_AF.txt ../data/TCAP_mutation_AF_patho_allMissense.txt 
Rscript annotate_pathogenecity_allMissense.R ../data/ANO5_mutation_AF.txt ../data/ANO5_mutation_AF_patho_allMissense.txt 
Rscript annotate_pathogenecity_allMissense.R ../data/SGCA_mutation_AF.txt ../data/SGCA_mutation_AF_patho_allMissense.txt 
Rscript annotate_pathogenecity_allMissense.R ../data/CAPN3_mutation_AF.txt ../data/CAPN3_mutation_AF_patho_allMissense.txt 
Rscript annotate_pathogenecity_allMissense.R ../data/SGCB_mutation_AF.txt ../data/SGCB_mutation_AF_patho_allMissense.txt 
Rscript annotate_pathogenecity_allMissense.R ../data/SGCD_mutation_AF.txt ../data/SGCD_mutation_AF_patho_allMissense.txt 
Rscript annotate_pathogenecity_allMissense.R ../data/SGCG_mutation_AF.txt ../data/SGCG_mutation_AF_patho_allMissense.txt 
Rscript annotate_pathogenecity_allMissense.R ../data/DYSF_mutation_AF.txt ../data/DYSF_mutation_AF_patho_allMissense.txt 
