Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/Data/CADD/FKRP_mutation_AF_CADD.txt /ysm-gpfs/scratch60/wl382/WES/Data/CADD/FKRP_mutation_AF_CADD_patho_20.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/Data/CADD/TCAP_mutation_AF_CADD.txt /ysm-gpfs/scratch60/wl382/WES/Data/CADD/TCAP_mutation_AF_CADD_patho_20.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/Data/CADD/ANO5_mutation_AF_CADD.txt /ysm-gpfs/scratch60/wl382/WES/Data/CADD/ANO5_mutation_AF_CADD_patho_20.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/Data/CADD/SGCA_mutation_AF_CADD.txt /ysm-gpfs/scratch60/wl382/WES/Data/CADD/SGCA_mutation_AF_CADD_patho_20.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/Data/CADD/CAPN3_mutation_AF_CADD.txt /ysm-gpfs/scratch60/wl382/WES/Data/CADD/CAPN3_mutation_AF_CADD_patho_20.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/Data/CADD/SGCB_mutation_AF_CADD.txt /ysm-gpfs/scratch60/wl382/WES/Data/CADD/SGCB_mutation_AF_CADD_patho_20.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/Data/CADD/SGCD_mutation_AF_CADD.txt /ysm-gpfs/scratch60/wl382/WES/Data/CADD/SGCD_mutation_AF_CADD_patho_20.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/Data/CADD/SGCG_mutation_AF_CADD.txt /ysm-gpfs/scratch60/wl382/WES/Data/CADD/SGCG_mutation_AF_CADD_patho_20.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/Data/CADD/DYSF_mutation_AF_CADD.txt /ysm-gpfs/scratch60/wl382/WES/Data/CADD/DYSF_mutation_AF_CADD_patho_20.txt 
