Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/prevalence_estimation/prevalence_estimation/extract_AF/data/FKRP_mutation_AF.txt ./data/FKRP_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/prevalence_estimation/prevalence_estimation/extract_AF/data/TCAP_mutation_AF.txt ./data/TCAP_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/prevalence_estimation/prevalence_estimation/extract_AF/data/ANO5_mutation_AF.txt ./data/ANO5_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/prevalence_estimation/prevalence_estimation/extract_AF/data/SGCA_mutation_AF.txt ./data/SGCA_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/prevalence_estimation/prevalence_estimation/extract_AF/data/CAPN3_mutation_AF.txt ./data/CAPN3_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/prevalence_estimation/prevalence_estimation/extract_AF/data/SGCB_mutation_AF.txt ./data/SGCB_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/prevalence_estimation/prevalence_estimation/extract_AF/data/SGCD_mutation_AF.txt ./data/SGCD_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/prevalence_estimation/prevalence_estimation/extract_AF/data/SGCG_mutation_AF.txt ./data/SGCG_mutation_AF_patho.txt 
Rscript annotate_pathogenecity.R /ysm-gpfs/scratch60/wl382/WES/prevalence_estimation/prevalence_estimation/extract_AF/data/SGCA_mutation_AF.txt ./data/SGCA_mutation_AF_patho.txt 
